name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: actions/checkout@v2

      - uses: snickerbockers/submodules-init@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/pkg/sdb-protobuf/

      - name: Build
        run: sh ./scripts/build_protobuf.sh

      - name: Build
        run: go build -v ./cmd/cli/cli.go