name: Go Release

on:
  release:
    types: [ published ]

jobs:

  release:
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go_version: [ 1.17 ]
        os: [ windows-latest ]

#        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -v ./cmd/cli/cli.go

      - name: Gzip
        run: |
          mkdir cli-${{ matrix.os }}
          cp cli cli-${{ matrix.os }}
          dir
          dir cli-${{ matrix.os }}
          tar -czvf cli-${{ matrix.os }}.tar.gz cli-${{ matrix.os }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cli-${{ matrix.os }}.tar.gz
          asset_name: cli-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}